### ISSUE TITLE
My Zigbee Valve configure Tile not working

### ISSUE THREAD

**Issue by Reid-n0rc** [constjs/jcdevhandlers#1]
When I press configure, nothing happens and the following is reported in the log

`6:57:22 PM: debug Parse returned null`
`6:57:22 PM: info catchall: 0000 8021 00 00 0040 00 F5B5 00 00 0000 00 0E 00`
`6:57:20 PM: debug configure()`

**Comment by jsconstantelos** [comment]
All the configure tile does is ensure the right parameters are set, and log a message. There's nothing in the phone app you'll see.

Is the device handler working to control the valve? If not, please watch the live logs and capture what you can. I used ST's base code from their Zigbee Valve device handler, so it should work.

**Comment by Reid-n0rc** [comment]
I've confirmed that the device handler is controlling the valve and the icons are updating in the app.
