### ISSUE TITLE
DTH Error - My GE Fan Control (Refresh Tile)

### ISSUE THREAD

**Issue by jordanal** [constjs/jcdevhandlers#13]
Hello,
I just started using your latest "my ge fan control" DTH which is working very well, thanks!

Thought you might want to know I get the following error in my Smartthings Live Log, every time I push the "Refresh" tile in the app.

7‎:‎45‎:‎26‎ ‎AM: debug Parse returned [Office Fan switch is on, Office Fan level is 99%]

7‎:‎45‎:‎26‎ ‎AM: debug parse() >> zwave.parse(zw device: BB, command: 2603, payload: 63 )

7‎:‎45‎:‎24‎ ‎AM: **error** groovy.lang.MissingPropertyException: No such property: value for class: physicalgraph.zwave.commands.manufacturerspecificv2.ManufacturerSpecificReport 

7‎:‎45‎:‎24‎ ‎AM: debug parse() >> zwave.parse(zw device: BB, command: 7205, payload: 00 63 49 44 31 31 ) 

7‎:‎45‎:‎24‎ ‎AM: debug Parse returned [Office Fan switch is on, Office Fan level is 99%] 

7‎:‎45‎:‎24‎ ‎AM: debug parse() >> zwave.parse(zw device: BB, command: 2603, payload: 63 ) 6df07b9b-5500-4af3-bd3d-5da1843b9802
‎
7‎:‎45‎:‎24‎ ‎AM: debug refresh() is called

**Comment by jsconstantelos** [comment]
I'm not seeing the error on any of the 4 devices I have.  Did you go into device preferences and validate your numbers are right AND tap on Save?

Here's that I see when tapping on refresh:

8:45:56 AM: debug Parse returned [Guest Bedroom Fan switch is off]
8:45:56 AM: debug parse() >> zwave.parse(zw device: 40, command: 2603, payload: 00 )

8:45:32 AM: debug Parse returned [Master Bedroom Fan switch is off]
8:45:32 AM: debug parse() >> zwave.parse(zw device: 25, command: 2603, payload: 00 )

8:49:16 AM: debug Parse returned [Master Bedroom Fan switch is on, Master Bedroom Fan level is 30%]
8:49:16 AM: debug parse() >> zwave.parse(zw device: 25, command: 2603, payload: 1E )
8:49:16 AM: debug refresh() is called
