### ISSUE TITLE
DuplicateKeyException when adding code via IDE

### ISSUE THREAD

**Issue by justintime** [constjs/jcdevhandlers#2]
After trying to create a new custom device handler via the IDE, I'm getting this exception:

```
Org.springframework.dao.DuplicateKeyException: a different object with the same identifier value was already associated with the session: [physicalgraph.device.CapabilityDeviceType#physicalgraph.device.CapabilityDeviceType : (unsaved)]; nested exception is org.hibernate.NonUniqueObjectException: a different object with the same identifier value was already associated with the session: [physicalgraph.device.CapabilityDeviceType#physicalgraph.device.CapabilityDeviceType : (unsaved)]
```

I don't have this device type already added.  This post from Tim Slagle seems to indicate it might be using a capability that isn't valid any longer? https://community.smartthings.com/t/creating-new-device-type-causes-an-error/28724/5?u=justintime

**Comment by justintime** [comment]
Sorry, forgot to mention this is the Aeon Metering Switch device handler.

**Comment by jsconstantelos** [comment]
I didn't see this notification until just now, so I apologize.  In that case, yes; but for the SES those are all the correct capabilities.  I did find that the capability "sensor" was there twice, so maybe that was it?  I just updated the device handler, so would you mind trying again?

**Comment by justintime** [comment]
That did allow me to save the CDH.  I published it for me, but when I go to use it for either of my two devices, it throws a 500 error when I try and switch the device type to this one.  Live Logging shows this when I hit the update button:

```
java.lang.NullPointerException: Cannot invoke method toByteArray() on null object @ line 332
```

**Comment by jsconstantelos** [comment]
It looks as though the default configuration values were not accepted for some reason.  Please go into the device in the phone app and "Edit Device".  You don't have to change anything if you don't want to, but live logging should report back something like this when you tap on Done:

![image](https://cloud.githubusercontent.com/assets/9900663/13411627/33635a64-df0c-11e5-8c02-1ef7b2689896.png)

**Comment by jsconstantelos** [comment]
@justintime , I believe I know what the issue is.  The default value for reporttype is 0, and that may be the issue.  I updated the code to make it a 1 ( you can change back to 0 if you want via the phone app).  Can you try the updated code?

**Comment by justintime** [comment]
After updating the CDH to your most recent version, I was getting the same problem.  I should have thought to try this sooner, but I then removed and readded the switch completely.  Doing that worked just the way it was supposed to.  Sorry for the noise!
