### ISSUE TITLE
Kwh and cost not showing up

### ISSUE THREAD

**Issue by ramikataya** [constjs/jcdevhandlers#5]
Hello,
The KWh and coat doesn't show up in the dashboard. See snapshot below.
Any idea why they are not showing up and only shown as '--'

Thanks
Rami

**Comment by ramikataya** [comment]
Sorry, I should have referenced the Aeon Smart Energy Meter 1st generation, I used the code that you posted.
Thx
Rami

**Comment by jsconstantelos** [comment]
You have either not updated/confirmed device preferences, or have not refreshed the device, or have not tapped on the Configure tile to make sure the HEM is properly configured, or you are running only on batteries.  If you have any more questions, check within the ST community where many others can help or where your questions may have already been answered:

https://community.smartthings.com/t/aeon-hem-v1-dh-discussion/60502

- JC
