### ISSUE TITLE
Doesn't work with ActionTiles

### ISSUE THREAD

**Issue by Stevenwsmtih** [constjs/jcdevhandlers#7]
Hi,

Thank you for creating this device handler for the Home Energy Monitor Gen1 at https://raw.githubusercontent.com/constjs/jcdevhandlers/master/devicetypes/jscgs350/my-aeon-home-energy-monitor-gen1.src/my-aeon-home-energy-monitor-gen1.groovy
I tried several and this is the only one that worked. However, I'd like for it to work with ActionTiles. I contacted their support and here's a cut and past of Terry's reply.:

>>>>>>>>>>>>>>>>>>>>>>
_As a "Works with SmartThings"™ partner, we try to be compatible with Things that conform to SmartThings standards.
 
In this case, the Device Type you linked to does not appear to be using the standard Attribute names required for Capability "Energy Meter" and Capability "Power Meter".

Here are the specs:

•	http://docs.smartthings.com/en/latest/capabilities-reference.html#energy-meter
•	http://docs.smartthings.com/en/latest/capabilities-reference.html#power-meter
In the DTH you linked...
attribute "currentKWH", "string" // Used to show current 
kWh since last resetattribute "currentWATTS", "string"// Used to show current watts being used on 
the main 
tile
The above need to be named "energy" and "power" respectively, and must be NUMBERS only._
>>>>>>>>>>>>>>>>>>>>>>>>

I'd really appreciate it if you could implement these changes so it is compatible with ActionTiles. 

Thank you,
Steve Smith

**Comment by okonon** [comment]
@Stevenwsmtih I am using @constjs 's script and i can't see any data reported from the device:
my setup:
Smart things hub v2
added device handler manually but there is not data being reported 


Any help will be appreciated

**Comment by jsconstantelos** [comment]
@okonon, I'm assuming you're not seeing updates in ST, not ActionTiles?  If so, rejoin the HEM, or look in the SmartThings community for more assistance.
