### ISSUE TITLE
Battery level is always at 0%

### ISSUE THREAD

**Issue by okonon** [constjs/jcdevhandlers#9]
@constjs  Thanks a lot for your DH! I love it. 
I was wondering if you could help me to guide me into right direction.

For some reason battery level for Aeon HEM v1 is showing 0% all the time. Any ideas why that may be?

P.S.: batteries are brand new
code for DH taken from here https://github.com/constjs/jcdevhandlers/tree/master/devicetypes/jscgs350/my-aeon-home-energy-monitor-gen1.src

**Comment by jsconstantelos** [comment]
You need to run the HEM on batteries for a while, depending upon what you've set for the battery reporting interval, and then the value will show up.  

Here's where can find more help:

https://community.smartthings.com/t/aeon-hem-v1-dh-updated-06-14-2017-discussion-dth-link-in-post-329/60502

**Comment by jsconstantelos** [comment]
Also, battery reporting on the HEM is useless, hence I think why Aeon didn't include that in all their other HEM versions.
